global:
  nameOverride: ""
  fullnameOverride: ""
  mainChart: hotelres
  replicas: 1
  imagePullPolicy: "IfNotPresent"
  imageRepo: "saurabhjha1/hotel-reservation"
  restartPolicy: Always
  serviceType: ClusterIP
  dockerRegistry: docker.io
  defaultImageVersion: latest
  serviceDnsDomain: "cluster.local"
  monitoring:
    defaultJaegerEnabled: true
    otelAddress: ""
    centralJaegerAddress: ""
    centralPrometheusAddress: ""
  services:
    environments:
      # TLS enablement
      #  - 0: Disable
      #  - 1: Enabled, using default cipher suite based on golang runtime
      #  - TLS_XXX: Enabled, using the specified Cipher suite, see tls/options.go#L22
      TLS: 0
      LOG_LEVEL: "INFO"
      JAEGER_SAMPLE_RATIO: "0.01"  # Can adjust sampling rate as needed
      MEMC_TIMEOUT: "2"
      GC: "100"
      # OpenTelemetry configurations
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.otel-demo.svc.cluster.local:4317"  # OpenTelemetry Collector endpoint
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"  # Using gRPC for OTLP
      OTEL_SERVICE_NAME: "hotel_reservation"  # Service name in traces
      OTEL_TRACES_SAMPLER: "parentbased_traceidratio"  # Sampling strategy
      OTEL_TRACES_SAMPLER_ARG: "0.01"  # Adjust sample rate as needed

  affinity: {}
  tolerations: []
  nodeSelector: {}

  memcached:
    HACount: 1
    environments:
      MEMCACHED_CACHE_SIZE: "128"
      MEMCACHED_THREADS: "2"
  
  mongodb:
    persistentVolume:               # use hostPath or pvprovisioner
      enabled: false
      size: "1Gi"
      hostPath:
        enabled: false
        path: /tmp
      pvprovisioner:
        enabled: false
        storageClassName: ceph-fs   # optional

loadgen:
  numThreads: "2"
  numConns: "4"
  duration: "30s"
  requestsPerSec: 200
  targetURL: ""
  scriptPath: "/wrk2/scripts/hotel-reservation/mixed-workload_type_1.lua"
  replicas: 1  # Number of replicas for the Deployment